### ISSUE TITLE
Overlapping tutorials

### ISSUE THREAD

**Issue by JohanvandenHeuvel** [APMLA-2021/APMLA-WS_21-22_material#1]
It seems that the tutorials for this course overlap with the tutorials of "Convex and Non-Convex Optimization" and "Beyond Fairness: a Socio-Technical view of Machine Learning". Could this maybe be changed?

**Comment by JohanvandenHeuvel** [comment]
Anything else then 14-16 would work. Apparently there are even more then 2 courses in the 14-16 time slot, so there is probably overlap for almost everyone taking this course.

**Comment by sandeep-ipk** [comment]
We would have at least one tutorial at 14-16 (either from convex optimization or beyond the fairness course). The convex optimization tutorial is broadcasted online, would it be possible if this tutorial from 16-18 also is broadcasted via zoom? Because traveling right after another tutorial ends is very difficult and we will lose a lot of time in between.
